"""add hmac rotation columns

Revision ID: 3e01fd2e5283
Revises: 7c55d5f7214e
Create Date: 2026-02-16 00:37:10.989035

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e01fd2e5283'
down_revision: Union[str, Sequence[str], None] = '7c55d5f7214e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairings', sa.Column('prev_hmac_secret', sa.Text(), nullable=True))
    op.add_column(
        'pairings', sa.Column('hmac_rotated_at', sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairings', 'hmac_rotated_at')
    op.drop_column('pairings', 'prev_hmac_secret')
    # ### end Alembic commands ###
