"""add cert columns to pairings

Revision ID: 7c55d5f7214e
Revises: 001
Create Date: 2026-02-16 00:25:30.289174

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c55d5f7214e'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairings', sa.Column('worker_cert', sa.Text(), nullable=True))
    op.add_column('pairings', sa.Column('worker_key', sa.Text(), nullable=True))
    op.add_column('pairings', sa.Column('controller_cert', sa.Text(), nullable=True))
    op.add_column('pairings', sa.Column('controller_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairings', 'controller_key')
    op.drop_column('pairings', 'controller_cert')
    op.drop_column('pairings', 'worker_key')
    op.drop_column('pairings', 'worker_cert')
    # ### end Alembic commands ###
